// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8utlbnuCq58w9Hg7Gn5Qk8WyN_XHu5XA',
    appId: '1:1011937071706:web:36d6a3a632777e3ebebe63',
    messagingSenderId: '1011937071706',
    projectId: 'todoapp-7d514',
    authDomain: 'todoapp-7d514.firebaseapp.com',
    storageBucket: 'todoapp-7d514.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsS-DRDpGRbcjAoOfH2iP8nGjkAqA0st8',
    appId: '1:1011937071706:android:f72b505373e34428bebe63',
    messagingSenderId: '1011937071706',
    projectId: 'todoapp-7d514',
    storageBucket: 'todoapp-7d514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQk9QNYaqLElSCtz_L2oSKcxEYF6Orxz8',
    appId: '1:1011937071706:ios:54c493f2a3848967bebe63',
    messagingSenderId: '1011937071706',
    projectId: 'todoapp-7d514',
    storageBucket: 'todoapp-7d514.appspot.com',
    iosBundleId: 'com.example.todoappnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQk9QNYaqLElSCtz_L2oSKcxEYF6Orxz8',
    appId: '1:1011937071706:ios:54c493f2a3848967bebe63',
    messagingSenderId: '1011937071706',
    projectId: 'todoapp-7d514',
    storageBucket: 'todoapp-7d514.appspot.com',
    iosBundleId: 'com.example.todoappnew',
  );
}
